version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: crypto-tracker-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: crypto-tracker
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - crypto-tracker-network

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: crypto-tracker-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - crypto-tracker-network

  # Backend API
  api:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: crypto-tracker-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/crypto-tracker?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./server:/app/server
      - /app/node_modules
    networks:
      - crypto-tracker-network

  # Frontend Client
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: crypto-tracker-client
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_WS_URL=ws://localhost:5000
    depends_on:
      - api
    volumes:
      - ./client:/app/client
      - /app/node_modules
    networks:
      - crypto-tracker-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: crypto-tracker-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
      - client
    networks:
      - crypto-tracker-network

volumes:
  mongodb_data:
  redis_data:

networks:
  crypto-tracker-network:
    driver: bridge